#!/usr/bin/env bash
# =============================================================================
# ratchet - .claude/hooks/checkpoint-evidence.sh
#
# Contract ............ CONTRACT.md §7.7 (checkpoint artifacts), §5.2
#                       (VERIFY_LAST is read, never re-derived)
# Invocation .......... checkpoint-evidence.sh <n> <stage>
#                       checkpoint-evidence.sh --selftest
# Blocking mechanism .. NONE. Exit 0 on success, 1 on usage/IO error.
#
# WHY THIS IS A SCRIPT AND NOT AN AGENT
#   The clear-reviewer judges a checkpoint from two documents: the scribe's
#   jump summary, and this evidence file. Its independence rests entirely on
#   the second document not having been written by the first author. If the
#   summarizer - or the orchestrator - could author or select the evidence,
#   the reviewer would be checking a claim against a restatement of the same
#   claim. So this file is machine-generated, says so on its first line, and
#   contains verbatim command output rather than any description of it.
#   The reviewer must spot-check at least one load-bearing claim from the
#   summary against this file and say which claim and what it found.
#
# STATE FILE OWNED BY THIS SCRIPT (§0.7)
# ---------------------------------------------------------------------------
# $CHECKPOINTS_DIR/<n>-<stage>-evidence.txt
#     Plain text, overwritten on each invocation for the same <n>-<stage>.
#     Line 1 is exactly:
#       SCRIPT-WRITTEN ONLY - generated by checkpoint-evidence.sh; do not edit
#     Then "key: value" header lines (checkpoint, stage, timestamp, epoch,
#     repo, branch, review_sha, base, merge_base), then these sections, each
#     introduced by a line of the form "== <TITLE> ==":
#       == GIT DIFF --STAT (merge-base..worktree) ==      verbatim
#       == GIT DIFF --NAME-ONLY (merge-base..worktree) == verbatim
#       == UNTRACKED (not ignored) ==                     verbatim
#       == COMMITS ON THIS BRANCH ==      one "sha subject" line per commit,
#                                          each followed by its file list
#                                          indented by four spaces
#       == VERIFY-LAST TAIL ==            the tail field of $VERIFY_LAST, or a
#                                          line saying the file is absent
#       == LEDGER ROW COUNTS ==           counts parsed from $FINDINGS
#       == MANIFEST ==                    plan-file and amendment line counts
#     A missing input is recorded as an explicit "(absent: <path>)" line. It
#     is never silently omitted - an evidence file that hides a gap is worse
#     than one that shows it.
#
#     <n> must be a decimal integer; <stage> is reduced to [a-z0-9._-] so the
#     filename cannot escape the checkpoints directory.
# =============================================================================

set -uo pipefail

RT_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || echo .)"

_bootstrap() {
  [ -r "$RT_SELF_DIR/ratchet.config.sh" ] || return 1
  # shellcheck disable=SC1090,SC1091
  . "$RT_SELF_DIR/ratchet.config.sh" || return 1
  local lib=""
  if [ -n "${HOOKS_DIR:-}" ] && [ -r "${HOOKS_DIR}/hooklib.sh" ]; then
    lib="${HOOKS_DIR}/hooklib.sh"
  elif [ -r "$RT_SELF_DIR/hooklib.sh" ]; then
    lib="$RT_SELF_DIR/hooklib.sh"
  fi
  if [ -n "$lib" ]; then
    # shellcheck disable=SC1090,SC1091
    . "$lib" || return 1
  fi
  command -v rt_repo_root >/dev/null 2>&1 && { rt_repo_root >/dev/null 2>&1 || true; }
  return 0
}

_abs() {
  case "$1" in
    /*|[A-Za-z]:[\\/]*) printf '%s' "$1" ;;
    *) printf '%s/%s' "${REPO_ROOT:-$PWD}" "$1" ;;
  esac
}
_now() { date -u +%s 2>/dev/null || echo 0; }
_now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || printf 'unknown'; }

_slug() { # stage -> safe filename component
  local s
  s="$(printf '%s' "${1:-}" | LC_ALL=C tr 'A-Z' 'a-z' | LC_ALL=C tr -c 'a-z0-9._-' '-')"
  s="${s##-}"; s="${s%%-}"
  printf '%s' "${s:0:40}"
}

_int_ok() {
  case "${1:-}" in (""|*[!0-9]*) return 1 ;; esac
  return 0
}

_section() { printf '\n== %s ==\n' "$1"; }

# The tail field of VERIFY_LAST. jq when present; a sed extraction otherwise,
# which is acceptable here because nothing security-relevant is being decided -
# this is evidence for a human reader, not a gate input.
_verify_tail() {
  local f="$1"
  if [ ! -r "$f" ]; then
    printf '(absent: %s - no deterministic gate result is on disk for this checkpoint)\n' "$f"
    return 0
  fi
  printf 'source: %s\n' "$f"
  if command -v jq >/dev/null 2>&1; then
    jq -r '"tier: \(.tier // "?")\nhead_sha: \(.head_sha // "?")\ndirty_hash: \(.dirty_hash // "?")\nexit: \(.exit // "?")\ntimestamp: \(.timestamp // "?")\n--- tail ---\n\(.tail // "")"' \
      "$f" 2>/dev/null && return 0
  fi
  sed 's/\r$//' "$f" 2>/dev/null | tr ',' '\n' | sed 's/^[[:space:]]*//'
  return 0
}

# Counts from the findings ledger (§7.4 frozen header).
_ledger_counts() {
  local f="$1" total=0 d
  if [ ! -r "$f" ]; then
    printf '(absent: %s - no findings ledger for this run)\n' "$f"
    return 0
  fi
  printf 'source: %s\n' "$f"
  total="$(grep -c '^|' "$f" 2>/dev/null)"
  case "$total" in (*[!0-9]*|"") total=0 ;; esac
  # header + separator are pipe rows too; report raw and adjusted.
  printf 'pipe rows (incl. header+separator): %s\n' "$total"
  for d in FIXED ACCEPTED DEFERRED WAIVED; do
    printf '%-9s %s\n' "$d:" "$(grep -c "|[[:space:]]*${d}[[:space:]]*|" "$f" 2>/dev/null)"
  done
  printf 'rows citing a DEC id: %s\n' "$(grep -c 'DEC-[0-9]' "$f" 2>/dev/null)"
  return 0
}

_manifest_counts() {
  local pf af
  pf="$(_abs "${PLAN_FILES:-.pipeline/plan-files.txt}")"
  af="$(_abs "${AMENDMENTS:-.pipeline/manifest-amendments.txt}")"
  if [ -r "$pf" ]; then
    printf 'plan-files (%s): %s path(s)\n' "$pf" "$(grep -c '[^[:space:]]' "$pf" 2>/dev/null)"
  else
    printf '(absent: %s)\n' "$pf"
  fi
  if [ -r "$af" ]; then
    printf 'amendments (%s): %s line(s)\n' "$af" "$(grep -c '[^[:space:]]' "$af" 2>/dev/null)"
    printf -- '--- amendment lines ---\n'
    sed 's/\r$//' "$af" 2>/dev/null | grep '[^[:space:]]'
  else
    printf '(absent: %s)\n' "$af"
  fi
  return 0
}

_selftest() {
  local fail=0 got
  got="$(_slug 'Security Audit/2')"
  [ "$got" = "security-audit-2" ] || { echo "FAIL slug: $got"; fail=1; }
  _int_ok 4 || { echo "FAIL int_ok 4"; fail=1; }
  if _int_ok "4a"; then echo "FAIL int_ok 4a"; fail=1; fi
  if _int_ok ""; then echo "FAIL int_ok empty"; fail=1; fi
  got="$(_verify_tail /nonexistent/verify-last.json)"
  case "$got" in "(absent:"*) : ;; *) echo "FAIL verify_tail absent: $got"; fail=1 ;; esac
  got="$(_ledger_counts /nonexistent/findings.md)"
  case "$got" in "(absent:"*) : ;; *) echo "FAIL ledger absent: $got"; fail=1 ;; esac
  if [ "$fail" -eq 0 ]; then echo "checkpoint-evidence.sh selftest PASS"; else echo "checkpoint-evidence.sh selftest FAIL"; fi
  return "$fail"
}

_usage() {
  cat <<'EOF'
usage: checkpoint-evidence.sh <n> <stage>
       checkpoint-evidence.sh --selftest

  <n>      decimal checkpoint number
  <stage>  short stage label, e.g. contracts-freeze, security-audit, pre-ship

Writes .pipeline/checkpoints/<n>-<stage>-evidence.txt. Script-written only:
the clear-reviewer's independence depends on this file not being authored by
the summarizer.
EOF
}

main() {
  case "${1:-}" in
    --selftest) _selftest; exit "$?" ;;
    -h|--help|"") _usage; [ -z "${1:-}" ] && exit 1; exit 0 ;;
  esac
  if [ "$#" -lt 2 ]; then _usage; exit 1; fi

  if ! _bootstrap; then
    printf 'checkpoint-evidence: the control layer could not be loaded from %s\n' "$RT_SELF_DIR" >&2
    exit 1
  fi

  local n stage dir out base mb head branch tmp
  n="$1"; stage="$(_slug "$2")"
  if ! _int_ok "$n"; then printf 'checkpoint-evidence: <n> must be a decimal integer, got "%s"\n' "$n" >&2; exit 1; fi
  if [ -z "$stage" ]; then printf 'checkpoint-evidence: <stage> reduced to an empty slug\n' >&2; exit 1; fi

  dir="$(_abs "${CHECKPOINTS_DIR:-.pipeline/checkpoints}")"
  mkdir -p "$dir" 2>/dev/null || { printf 'checkpoint-evidence: cannot create %s\n' "$dir" >&2; exit 1; }
  out="$dir/$n-$stage-evidence.txt"
  tmp="$out.tmp.$$"

  base="${BASE_BRANCH:-main}"
  head="NO-HEAD"; branch="UNKNOWN"; mb=""
  if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    head="$(git rev-parse HEAD 2>/dev/null)"; [ -n "$head" ] || head="NO-HEAD"
    branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"; [ -n "$branch" ] || branch="DETACHED"
    if git rev-parse --verify --quiet "$base" >/dev/null 2>&1; then
      mb="$(git merge-base "$base" HEAD 2>/dev/null)"
    fi
  fi

  {
    printf 'SCRIPT-WRITTEN ONLY - generated by checkpoint-evidence.sh; do not edit\n'
    printf 'checkpoint: %s\n' "$n"
    printf 'stage: %s\n' "$stage"
    printf 'timestamp: %s\n' "$(_now_iso)"
    printf 'epoch: %s\n' "$(_now)"
    printf 'project: %s\n' "${PROJECT_NAME:-unknown}"
    printf 'repo: %s\n' "${REPO_ROOT:-$PWD}"
    printf 'branch: %s\n' "$branch"
    printf 'review_sha: %s\n' "$head"
    printf 'base: %s\n' "$base"
    printf 'merge_base: %s\n' "${mb:-NONE}"
    printf 'milestone: %s\n' "$(sed 's/\r$//' "$(_abs "${RUN_ACTIVE:-.pipeline/run-active}")" 2>/dev/null | head -n 1)"

    if [ "$head" = "NO-HEAD" ]; then
      _section 'GIT'
      printf '(absent: git is unavailable or this is not a work tree - no diff evidence exists)\n'
    else
      _section 'GIT DIFF --STAT (merge-base..worktree)'
      if [ -n "$mb" ]; then git diff --stat "$mb" 2>/dev/null
      else printf '(no merge base with %s; showing diff against HEAD)\n' "$base"; git diff --stat HEAD 2>/dev/null; fi

      _section 'GIT DIFF --NAME-ONLY (merge-base..worktree)'
      if [ -n "$mb" ]; then git diff --name-only "$mb" 2>/dev/null
      else git diff --name-only HEAD 2>/dev/null; fi

      _section 'UNTRACKED (not ignored)'
      git ls-files --others --exclude-standard 2>/dev/null

      _section 'COMMITS ON THIS BRANCH'
      if [ -n "$mb" ]; then
        local sha
        git log --format='%H %s' "$mb..HEAD" 2>/dev/null | while IFS= read -r line; do
          printf '%s\n' "$line"
          sha="${line%% *}"
          git show --pretty=format: --name-only "$sha" 2>/dev/null \
            | grep -v '^[[:space:]]*$' | sed 's/^/    /'
        done
      else
        printf '(no merge base with %s - cannot bound this branch commit list)\n' "$base"
      fi
    fi

    _section 'VERIFY-LAST TAIL'
    _verify_tail "$(_abs "${VERIFY_LAST:-.pipeline/verify-last.json}")"

    _section 'LEDGER ROW COUNTS'
    _ledger_counts "$(_abs "${FINDINGS:-.pipeline/findings.md}")"

    _section 'MANIFEST'
    _manifest_counts

    _section 'END'
  } > "$tmp" 2>/dev/null

  mv -f "$tmp" "$out" 2>/dev/null || { rm -f "$tmp" 2>/dev/null; printf 'checkpoint-evidence: cannot write %s\n' "$out" >&2; exit 1; }
  printf '%s\n' "$out"
  if [ -r "$RT_SELF_DIR/pipeline-event.sh" ]; then
    bash "$RT_SELF_DIR/pipeline-event.sh" checkpoint_evidence \
      "checkpoint=$n" "stage=$stage" "review_sha=$head" >/dev/null 2>&1 || true
  fi
  exit 0
}

main "$@"
