#!/usr/bin/env bash
# =============================================================================
# ratchet - .claude/hooks/dispatch-baseline.sh
#
# Contract ............ CONTRACT.md §5.4 (attribution modes and the measured
#                       env-var caveat), §3 (manual, agent-invocable)
# Invocation .......... dispatch-baseline.sh <dispatch-id> [partition-glob...]
#                       dispatch-baseline.sh changed [<dispatch-id>]
#                       dispatch-baseline.sh --selftest
# Blocking mechanism .. NONE. Exit 0 on success, 1 on a usage or IO error.
#                       Nothing here decides safety; it records evidence that
#                       lets the SubagentStop gates decide correctly.
#
# WHY THIS EXISTS
#   PIPELINE_DISPATCH_ID and PIPELINE_PARTITION_GLOB do NOT reliably reach hook
#   environments from the Agent tool (measured). A gate that trusts the env
#   sees nothing and falls back to diffing the whole working tree, which hands
#   an arriving agent every pre-existing change as its own. So the orchestrator
#   writes the identity to DISK before dispatching, and the gates read files.
#
# STATE FILES OWNED BY THIS SCRIPT (§0.7 - this script is also their reader,
# via the `changed` subcommand, which is what the gates call)
# ---------------------------------------------------------------------------
# $DISPATCH_DIR/current
#     One line: the dispatch id of the most recent dispatch. Overwritten by
#     every dispatch. Cleared by gc-prune.sh archive.
#
# $DISPATCH_DIR/<id>.glob
#     One partition glob per line, in the order given on the command line.
#     Empty file = no glob was supplied, which downgrades attribution from
#     `sound` to `weak` and the gates say so out loud.
#
# $DISPATCH_DIR/<id>.snapshot          (the pre-dispatch snapshot; feeds mode `exact`)
#     Header lines "key: value", then a fixed separator, then one record per
#     ALREADY-DIRTY path at dispatch time:
#
#       # ratchet dispatch baseline - written by dispatch-baseline.sh
#       schema: 1
#       dispatch: <id>
#       timestamp: <ISO-8601 UTC>
#       epoch: <decimal seconds>
#       head: <full HEAD sha | NO-HEAD>
#       branch: <branch name | DETACHED>
#       count: <number of records below>
#       --- dirty ---
#       <XY><TAB><blob-sha1 | -><TAB><repo-relative path>
#
#     XY       two-character `git status --porcelain` code, spaces preserved
#     blob-sha1 `git hash-object` of the WORKING-TREE file at dispatch time,
#               or "-" when the file does not exist (deleted) or cannot be
#               hashed.
#     Snapshotting only the dirty set is deliberate: it is bounded by what is
#     actually dirty rather than by repo size, and it is exactly the
#     information the gates lacked. A path that was dirty at dispatch AND has
#     the same content now is provably not this agent's work; a path that was
#     dirty with different content, or was not dirty at all, is.
#
# $DISPATCH_DIR/<id>.baseline          (DERIVED, and deliberately not written
#                                       at dispatch time)
#     A plain newline list of repo-relative paths that ARE attributable to this
#     dispatch, regenerated by `dispatch-baseline.sh changed` every time it
#     runs. This is the shape hooklib's rt_dispatch_baseline/rt_attributable
#     read (they grep -Fqx a path against it), so the two readers agree.
#     It is NOT written by the snapshot step: at dispatch time nothing has
#     changed yet, and an EMPTY baseline would tell rt_attributable that every
#     path is "provably not this agent's" - silently disabling the law 1
#     backstop in the one mode that is supposed to be strongest. With no
#     .baseline on disk attribution degrades to `sound`, which is honest.
#     The SubagentStop gates call `changed` before attributing, so exact mode
#     is available exactly when it is correct.
#
# $DISPATCH_DIR/<id>.meta
#     "key: value" lines: dispatch, epoch, head, globs (count), argv.
# =============================================================================

set -uo pipefail

RT_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || echo .)"

_bootstrap() {
  [ -r "$RT_SELF_DIR/ratchet.config.sh" ] || return 1
  # shellcheck disable=SC1090,SC1091
  . "$RT_SELF_DIR/ratchet.config.sh" || return 1
  local lib=""
  if [ -n "${HOOKS_DIR:-}" ] && [ -r "${HOOKS_DIR}/hooklib.sh" ]; then
    lib="${HOOKS_DIR}/hooklib.sh"
  elif [ -r "$RT_SELF_DIR/hooklib.sh" ]; then
    lib="$RT_SELF_DIR/hooklib.sh"
  fi
  if [ -n "$lib" ]; then
    # shellcheck disable=SC1090,SC1091
    . "$lib" || return 1
  fi
  command -v rt_repo_root >/dev/null 2>&1 && { rt_repo_root >/dev/null 2>&1 || true; }
  return 0
}

_abs() {
  case "$1" in
    /*|[A-Za-z]:[\\/]*) printf '%s' "$1" ;;
    *) printf '%s/%s' "${REPO_ROOT:-$PWD}" "$1" ;;
  esac
}
_now() { date -u +%s 2>/dev/null || echo 0; }
_now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || printf 'unknown'; }
_dir() {
  local d; d="$(_abs "${DISPATCH_DIR:-${PIPELINE_DIR:-.pipeline}/dispatch}")"
  mkdir -p "$d" 2>/dev/null || true
  printf '%s' "$d"
}
_read_first_line() {
  local f="$1" line=""
  [ -r "$f" ] || return 1
  IFS= read -r line < "$f" 2>/dev/null || true
  printf '%s' "${line//$'\r'/}"
}
_event() {
  local t="$1"; shift
  if [ -r "$RT_SELF_DIR/pipeline-event.sh" ]; then
    bash "$RT_SELF_DIR/pipeline-event.sh" "$t" "$@" >/dev/null 2>&1 || true
  fi
  return 0
}

# id charset: a filename component, nothing clever. Rejects path separators,
# leading dots and anything that could escape the dispatch directory.
_id_valid() {
  local id="$1"
  case "$id" in
    "" ) return 1 ;;
    *[/\\]* ) return 1 ;;
    .* ) return 1 ;;
  esac
  printf '%s' "$id" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'
}

_usage() {
  cat <<'EOF'
usage:
  dispatch-baseline.sh <dispatch-id> [partition-glob ...]
      Snapshot the tree and record the partition globs for a dispatch.
      Run this immediately BEFORE dispatching the agent.

  dispatch-baseline.sh changed [<dispatch-id>]
      Print the repo-relative paths that changed since that dispatch's
      snapshot, one per line, AND refresh <id>.baseline with that list so
      hooklib's rt_attributable can run in exact mode. This is the reader for
      the .snapshot format. Defaults to the id in dispatch/current.

  dispatch-baseline.sh --selftest
EOF
}

# --- writer ---------------------------------------------------------------- #
_snapshot() { # <id> [globs...]
  local id="$1"; shift
  local d tree glob meta head branch line xy path blob count=0 tmp
  d="$(_dir)"
  tree="$d/$id.snapshot"; glob="$d/$id.glob"; meta="$d/$id.meta"
  # A derived baseline from an EARLIER dispatch that reused this id would be
  # read as this dispatch's answer. Remove it; `changed` regenerates it.
  rm -f "$d/$id.baseline" 2>/dev/null || true

  if ! command -v git >/dev/null 2>&1 || ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    printf 'dispatch-baseline: not a git work tree (or git missing); no snapshot written.\n' >&2
    printf 'Attribution for this dispatch will degrade to `sound` (glob) or `weak`.\n' >&2
    : > "$glob" 2>/dev/null || true
    if [ "$#" -gt 0 ]; then printf '%s\n' "$@" > "$glob" 2>/dev/null || true; fi
    printf '%s\n' "$id" > "$d/current" 2>/dev/null || true
    return 1
  fi

  head="$(git rev-parse HEAD 2>/dev/null)"; [ -n "$head" ] || head="NO-HEAD"
  branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
  [ -n "$branch" ] && [ "$branch" != "HEAD" ] || branch="DETACHED"

  tmp="$tree.tmp.$$"
  : > "$tmp" 2>/dev/null || { printf 'dispatch-baseline: cannot write %s\n' "$tmp" >&2; return 1; }
  local records="$tmp.rec"
  : > "$records" 2>/dev/null || true
  while IFS= read -r line; do
    line="${line%$'\r'}"
    [ -n "$line" ] || continue
    xy="${line:0:2}"
    path="${line:3}"
    # rename/copy records read "old -> new"; the new name is what matters.
    case "$path" in *' -> '*) path="${path##* -> }" ;; esac
    path="${path%\"}"; path="${path#\"}"
    blob="-"
    if [ -f "$path" ]; then
      blob="$(git hash-object -- "$path" 2>/dev/null)"; [ -n "$blob" ] || blob="-"
    fi
    printf '%s\t%s\t%s\n' "$xy" "$blob" "$path" >> "$records" 2>/dev/null || true
    count=$((count+1))
  done < <(git status --porcelain -uall 2>/dev/null)

  {
    printf '# ratchet dispatch baseline - written by dispatch-baseline.sh\n'
    printf 'schema: 1\n'
    printf 'dispatch: %s\n' "$id"
    printf 'timestamp: %s\n' "$(_now_iso)"
    printf 'epoch: %s\n' "$(_now)"
    printf 'head: %s\n' "$head"
    printf 'branch: %s\n' "$branch"
    printf 'count: %s\n' "$count"
    printf -- '--- dirty ---\n'
    cat "$records" 2>/dev/null
  } > "$tmp" 2>/dev/null
  mv -f "$tmp" "$tree" 2>/dev/null || { rm -f "$tmp" "$records" 2>/dev/null; return 1; }
  rm -f "$records" 2>/dev/null || true

  : > "$glob" 2>/dev/null || true
  if [ "$#" -gt 0 ]; then printf '%s\n' "$@" >> "$glob" 2>/dev/null || true; fi
  printf '%s\n' "$id" > "$d/current" 2>/dev/null || true
  {
    printf 'dispatch: %s\n' "$id"
    printf 'epoch: %s\n' "$(_now)"
    printf 'head: %s\n' "$head"
    printf 'globs: %s\n' "$#"
    printf 'argv: %s\n' "$*"
  } > "$meta" 2>/dev/null || true

  printf 'dispatch-baseline: %s recorded (head %s, %s dirty path(s), %s glob(s)).\n' \
    "$id" "${head:0:12}" "$count" "$#"
  if [ "$#" -eq 0 ]; then
    printf 'dispatch-baseline: WARNING - no partition glob given. scope-guard cannot bound this\n' >&2
    printf 'agent, and attribution loses its `sound` fallback. Pass the globs for this seat.\n' >&2
  fi
  _event dispatch_baseline "dispatch=$id" "head=$head" "dirty=$count" "globs=$#"
  return 0
}

# --- reader ---------------------------------------------------------------- #
# Prints paths that changed since the baseline. A path is NOT this agent's if
# it was dirty at dispatch with the SAME content it has now.
#
# $PIPELINE_DIR is filtered out of the result. Two reasons, both measured on
# the first run of this reader: the harness writes its own scratch there
# constantly (events log, counters, and this function's own temp files), so an
# unfiltered list attributes the gate's bookkeeping to the agent it is
# judging; and in a repo where .pipeline is not gitignored that noise is the
# MAJORITY of the list, burying the real finding. Scratch is scope-exempt
# everywhere else in the harness for the same reason.
_changed_since() { # <id>
  local id="$1" d tree line xy blob path now_blob key derived
  d="$(_dir)"; tree="$d/$id.snapshot"; derived="$d/$id.baseline"
  command -v git >/dev/null 2>&1 || return 1
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 1

  local base_head="" baseline="$tree.read.$$"
  : > "$baseline" 2>/dev/null || true
  if [ -r "$tree" ]; then
    base_head="$(sed -n 's/^head: //p' "$tree" 2>/dev/null | head -n 1)"
    sed -n '/^--- dirty ---$/,$p' "$tree" 2>/dev/null | sed '1d' > "$baseline" 2>/dev/null || true
  fi

  {
    git status --porcelain -uall 2>/dev/null | while IFS= read -r line; do
      line="${line%$'\r'}"; [ -n "$line" ] || continue
      path="${line:3}"
      case "$path" in *' -> '*) path="${path##* -> }" ;; esac
      path="${path%\"}"; path="${path#\"}"
      now_blob="-"
      [ -f "$path" ] && { now_blob="$(git hash-object -- "$path" 2>/dev/null)"; [ -n "$now_blob" ] || now_blob="-"; }
      key="$(grep -F -- "$(printf '\t')$path" "$baseline" 2>/dev/null | head -n 1)"
      if [ -n "$key" ]; then
        blob="$(printf '%s' "$key" | cut -f2)"
        [ "$blob" = "$now_blob" ] && continue   # unchanged since dispatch
      fi
      printf '%s\n' "$path"
    done
    # Commits made since the baseline head belong to this dispatch too.
    if [ -n "$base_head" ] && [ "$base_head" != "NO-HEAD" ]; then
      if git rev-parse --verify --quiet "$base_head" >/dev/null 2>&1; then
        git diff --name-only "$base_head" HEAD 2>/dev/null
      fi
    fi
  } | sed 's/\r$//' | sed 's#^\./##' | grep -v '^[[:space:]]*$' \
    | grep -v -e "^${PIPELINE_DIR:-.pipeline}/" | sort -u > "$derived.tmp.$$" 2>/dev/null
  rm -f "$baseline" 2>/dev/null || true
  # Publish the derived list for hooklib's exact mode, then print it.
  mv -f "$derived.tmp.$$" "$derived" 2>/dev/null || rm -f "$derived.tmp.$$" 2>/dev/null
  cat "$derived" 2>/dev/null
  return 0
}

_selftest() {
  local fail=0
  _id_valid "p1-developer" || { echo "FAIL id_valid ok-name"; fail=1; }
  _id_valid "M1.p2_dev-3"  || { echo "FAIL id_valid dots"; fail=1; }
  if _id_valid "../escape";  then echo "FAIL id_valid traversal"; fail=1; fi
  if _id_valid "a/b";        then echo "FAIL id_valid slash"; fail=1; fi
  if _id_valid ".hidden";    then echo "FAIL id_valid leading dot"; fail=1; fi
  if _id_valid "";           then echo "FAIL id_valid empty"; fail=1; fi
  if _id_valid "has space";  then echo "FAIL id_valid space"; fail=1; fi
  if _id_valid "$(printf 'x%.0s' $(seq 1 80))"; then echo "FAIL id_valid overlong"; fail=1; fi
  if [ "$fail" -eq 0 ]; then echo "dispatch-baseline.sh selftest PASS"; else echo "dispatch-baseline.sh selftest FAIL"; fi
  return "$fail"
}

main() {
  case "${1:-}" in
    --selftest) _selftest; exit "$?" ;;
    -h|--help|"") _usage; [ -z "${1:-}" ] && exit 1; exit 0 ;;
  esac

  if ! _bootstrap; then
    printf 'dispatch-baseline: the control layer could not be loaded from %s\n' "$RT_SELF_DIR" >&2
    exit 1
  fi

  if [ "$1" = "changed" ]; then
    local id="${2:-}"
    [ -n "$id" ] || id="$(_read_first_line "$(_dir)/current" 2>/dev/null)"
    if ! _id_valid "$id"; then
      printf 'dispatch-baseline: no usable dispatch id for `changed`\n' >&2
      exit 1
    fi
    _changed_since "$id"
    exit 0
  fi

  local id="$1"; shift
  if ! _id_valid "$id"; then
    printf 'dispatch-baseline: invalid dispatch id %s\n' "$id" >&2
    printf 'Ids must match ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ - no slashes, no leading dot.\n' >&2
    exit 1
  fi
  _snapshot "$id" "$@"
  exit 0
}

main "$@"
