#!/usr/bin/env bash
# ratchet.config.sh - CORE configuration for the Ratchet harness (CONTRACT SS2.1).
# HUMANS: do not edit this file. It is control-set / Tier 2b and never escalatable.
#         To change a value, export it in the environment - every variable below is ${VAR:-default}.
# ---------------------------------------------------------------------------------------------
# Contract of this file:
#   1. Resolve REPO_ROOT (CLAUDE_PROJECT_DIR > BASH_SOURCE walk-up > git rev-parse) and cd to it,
#      so every other path in the harness can stay repo-relative.
#   2. Define every FROZEN core variable from CONTRACT SS2.1, each environment-overridable.
#   3. Source the DOMAIN pack (domain.config.sh) and then the selected STACK pack.
#   4. Be idempotent: sourcing twice is a no-op.
# This file is SOURCED, never executed by the hooks. It therefore sets no shell options
# (set -u / set -e in a sourced file would leak into every caller).
# Executing it directly with --selftest prints the resolved configuration and exits 0.
# ---------------------------------------------------------------------------------------------

# --- idempotence guard --------------------------------------------------------------------
if [ -n "${RATCHET_CONFIG_LOADED:-}" ]; then
  return 0 2>/dev/null || exit 0
fi
RATCHET_CONFIG_LOADED=1

RT_VERSION="${RT_VERSION:-1.2.2}"

# --- REPO_ROOT resolution -------------------------------------------------------------------
# Order is fixed by CONTRACT SS4.1: CLAUDE_PROJECT_DIR, then a walk-up from this file, then git.
# The walk-up exists because Git-Bash hook invocations do not always carry CLAUDE_PROJECT_DIR and
# may run with a cwd anywhere inside (or outside) the tree.
_rt_cfg_source="${BASH_SOURCE[0]:-$0}"

_rt_resolve_root() {
  local d p c
  # CLAUDE_PROJECT_DIR arrives in the CALLER's dialect, which is not always this shell's: Claude
  # Code running on Windows hands a WSL-hosted hook "C:\repo", where -d is false and this used to
  # fall through to the walk-up silently. hooklib.sh's rt_canon_abs is the full six-dialect
  # reduction, but it is not sourced yet here, so this is the same idea in a few lines: try the
  # value as given, then the obvious re-spellings, and take the first that is really a directory.
  if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
    for c in "${CLAUDE_PROJECT_DIR}" "${CLAUDE_PROJECT_DIR//\\//}"; do
      [ -n "$c" ] && [ -d "$c" ] && { ( cd "$c" 2>/dev/null && pwd ) && return 0; }
    done
    c="${CLAUDE_PROJECT_DIR//\\//}"
    case "$c" in
      [A-Za-z]:/*)
        d=${c%%:*}; d=${d,,}; p=${c#*:}
        for c in "/mnt/${d}${p}" "/${d}${p}" "/cygdrive/${d}${p}"; do
          [ -d "$c" ] && { ( cd "$c" 2>/dev/null && pwd ) && return 0; }
        done ;;
    esac
  fi
  d=$( cd "$(dirname "${_rt_cfg_source}")" 2>/dev/null && pwd )
  while [ -n "$d" ]; do
    if [ -d "$d/.claude/hooks" ] || [ -d "$d/.git" ]; then
      printf '%s\n' "$d"; return 0
    fi
    p=$(dirname "$d")
    [ "$p" = "$d" ] && break
    d="$p"
  done
  if command -v git >/dev/null 2>&1; then
    d=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$d" ]; then printf '%s\n' "$d"; return 0; fi
  fi
  pwd
}

REPO_ROOT="${REPO_ROOT:-$(_rt_resolve_root)}"
# Strip a stray CR that a Windows editor may have left in an exported value.
REPO_ROOT="${REPO_ROOT%$'\r'}"
if [ -d "$REPO_ROOT" ]; then
  cd "$REPO_ROOT" 2>/dev/null || :
  REPO_ROOT="$(pwd)"
fi
export REPO_ROOT

PROJECT_NAME="${PROJECT_NAME:-$(basename "$REPO_ROOT")}"
ESCALATION_MODE="${ESCALATION_MODE:-light}"   # light | strict

# --- directories (repo-relative; we are cd'd to REPO_ROOT) ----------------------------------
PIPELINE_DIR="${PIPELINE_DIR:-.pipeline}"
CONTEXT_DIR="${CONTEXT_DIR:-.context}"
DEV_DIR="${DEV_DIR:-.agent-development}"
CLAUDE_DIR="${CLAUDE_DIR:-.claude}"
HOOKS_DIR="${HOOKS_DIR:-$CLAUDE_DIR/hooks}"
EVIDENCE_DIR="${EVIDENCE_DIR:-docs/evidence}"
SECRETS_DIR="${SECRETS_DIR:-secrets}"

# --- run-scoped state files -----------------------------------------------------------------
RUN_ACTIVE="${RUN_ACTIVE:-$PIPELINE_DIR/run-active}"
RUN_START="${RUN_START:-$PIPELINE_DIR/run-start}"
RUN_IDLE="${RUN_IDLE:-$PIPELINE_DIR/run-idle}"
RUN_LAST_SEEN="${RUN_LAST_SEEN:-$PIPELINE_DIR/run-last-seen}"
READY_TO_SHIP="${READY_TO_SHIP:-$PIPELINE_DIR/ready-to-ship}"
PLAN_FILES="${PLAN_FILES:-$PIPELINE_DIR/plan-files.txt}"
AMENDMENTS="${AMENDMENTS:-$PIPELINE_DIR/manifest-amendments.txt}"
FINDINGS="${FINDINGS:-$PIPELINE_DIR/findings.md}"
VERIFY_LAST="${VERIFY_LAST:-$PIPELINE_DIR/verify-last.json}"
RED_BASELINE="${RED_BASELINE:-$PIPELINE_DIR/red-baseline.txt}"
SHIP_CONSENT="${SHIP_CONSENT:-$PIPELINE_DIR/ship-consent.json}"
RECAP="${RECAP:-$PIPELINE_DIR/recap.md}"
CHECKPOINTS_DIR="${CHECKPOINTS_DIR:-$PIPELINE_DIR/checkpoints}"
ESCALATIONS_DIR="${ESCALATIONS_DIR:-$PIPELINE_DIR/escalations}"
EVENTS_LOG="${EVENTS_LOG:-$PIPELINE_DIR/run-events.jsonl}"
METRICS_JSON="${METRICS_JSON:-$PIPELINE_DIR/run-metrics.json}"
CMD_LOG="${CMD_LOG:-$PIPELINE_DIR/cmd-log}"
RUN_JOURNAL="${RUN_JOURNAL:-$PIPELINE_DIR/run-journal.md}"
CONTEXT_LIVE="${CONTEXT_LIVE:-$PIPELINE_DIR/context-live.md}"
ACTIVE_LESSONS="${ACTIVE_LESSONS:-$DEV_DIR/ACTIVE-LESSONS.md}"
PENDING_ACTIONS="${PENDING_ACTIONS:-$DEV_DIR/PENDING-HUMAN-ACTIONS.md}"

# Dispatch attribution store (CONTRACT SS5.4 env-var caveat: hooks read the FILES, env is fallback).
#   $DISPATCH_DIR/current      -> the id of the dispatch currently in flight
#   $DISPATCH_DIR/<id>.glob    -> that dispatch's write allow-list, one glob per line
#   $DISPATCH_DIR/<id>.baseline-> tree snapshot written by dispatch-baseline.sh (enables exact mode)
DISPATCH_DIR="${DISPATCH_DIR:-$PIPELINE_DIR/dispatch}"

# --- git / forge ------------------------------------------------------------------------------
BASE_BRANCH="${BASE_BRANCH:-main}"
AGENT_BRANCH_PREFIX="${AGENT_BRANCH_PREFIX:-agent/}"

# --- caps & budgets ---------------------------------------------------------------------------
MAX_STOP_RETRIES="${MAX_STOP_RETRIES:-3}"
MAX_SUBAGENT_RETRIES="${MAX_SUBAGENT_RETRIES:-3}"
MAX_REVIEW_ROUNDS="${MAX_REVIEW_ROUNDS:-2}"
MAX_RUN_WORK_SECONDS="${MAX_RUN_WORK_SECONDS:-28800}"
MAX_RUN_WALL_SECONDS="${MAX_RUN_WALL_SECONDS:-604800}"
IDLE_THRESHOLD_SECONDS="${IDLE_THRESHOLD_SECONDS:-900}"

# --- narrative caps ---------------------------------------------------------------------------
CAP_RATIONALE_FIXED="${CAP_RATIONALE_FIXED:-40}"
CAP_RATIONALE_ACCEPTED="${CAP_RATIONALE_ACCEPTED:-80}"
CAP_CHECKPOINT_SUMMARY="${CAP_CHECKPOINT_SUMMARY:-500}"
CAP_CLEAR_VERDICT="${CAP_CLEAR_VERDICT:-200}"
CAP_RECAP_WORDS="${CAP_RECAP_WORDS:-400}"
CAP_RETRO_LINES="${CAP_RETRO_LINES:-220}"
CAP_ACTIVE_LESSONS_LINES="${CAP_ACTIVE_LESSONS_LINES:-100}"
# session-start.sh's own injection backstop, matching the 150-line threshold
# PIPELINE.md's garbage-collection table already uses to trigger gc-prune.sh
# rewriting context-live.md. That trigger keeps the FILE short; this cap
# keeps the INJECTION short even in the gap before the next prune fires.
CAP_CONTEXT_LIVE_LINES="${CAP_CONTEXT_LIVE_LINES:-150}"
DECISIONS_HOT_SOFT_LINES="${DECISIONS_HOT_SOFT_LINES:-250}"
DECISIONS_HOT_HARD_LINES="${DECISIONS_HOT_HARD_LINES:-300}"

# --- escalation --------------------------------------------------------------------------------
ESCALATION_KEY="${ESCALATION_KEY:-$SECRETS_DIR/escalation.key}"
ESCALATION_TTL_SECONDS="${ESCALATION_TTL_SECONDS:-1800}"
ESCALATION_LEDGER="${ESCALATION_LEDGER:-$ESCALATIONS_DIR/ledger.jsonl}"

# --- notification --------------------------------------------------------------------------------
RATCHET_WEBHOOK_URL="${RATCHET_WEBHOOK_URL:-}"   # https only; unset disables the pager

# --- harness-fixed protected sets (NOT domain-configurable) ---------------------------------------
# CONTRACT SS5.6: the control set can never be lifted by any approval, card or domain pack.
# Matched only when the path is under $CLAUDE_DIR, so an unrelated repo file named settings.json
# (e.g. .vscode/settings.json) is not swept up.
CONTROL_SET="${CONTROL_SET:-settings.json
guard.sh
scope-guard.sh
hooklib.sh
escalation-lib.sh
approve.sh
ratchet.config.sh}"

# Path prefixes that are always in scope: agent scratch, the learning loop, and evidence.
# These are exempt from manifest membership (they are not part of any milestone's file plan).
SCOPE_EXEMPT_PREFIXES="${SCOPE_EXEMPT_PREFIXES:-$PIPELINE_DIR/
$DEV_DIR/
$EVIDENCE_DIR/}"

# --- domain pack ------------------------------------------------------------------------------
# The init interview rewrites domain.config.sh. An absent pack is not fatal: the harness still
# protects secrets, the governing corpus and the control layer from its own defaults.
RATCHET_DOMAIN_CONFIG="${RATCHET_DOMAIN_CONFIG:-$HOOKS_DIR/domain.config.sh}"
if [ -f "$RATCHET_DOMAIN_CONFIG" ]; then
  # shellcheck source=domain.config.sh disable=SC1090
  . "$RATCHET_DOMAIN_CONFIG"
else
  printf 'ratchet: NOTICE no domain pack at %s - running with empty domain lists\n' \
    "$RATCHET_DOMAIN_CONFIG" >&2
  DOMAIN_NAME="${DOMAIN_NAME:-none}"
  FORBIDDEN_EXEC_TOKENS="${FORBIDDEN_EXEC_TOKENS:-}"
  FORBIDDEN_ARTIFACTS="${FORBIDDEN_ARTIFACTS:-}"
  BANNED_READ_FILES="${BANNED_READ_FILES:-}"
  GOVERNING_CORPUS="${GOVERNING_CORPUS:-}"
  SECRET_PATTERNS="${SECRET_PATTERNS:-.env
.env.*
secrets/
*.pem
*.key
*.p8
id_rsa*}"
  SECRET_EXEMPTIONS="${SECRET_EXEMPTIONS:-.env.example
.env.sample}"
  DOMAIN_NEVER_ESCALATABLE="${DOMAIN_NEVER_ESCALATABLE:-}"
  DOMAIN_LAWS="${DOMAIN_LAWS:-}"
  DOMAIN_REVIEW_LENS="${DOMAIN_REVIEW_LENS:-}"
  DOMAIN_SECURITY_PASS="${DOMAIN_SECURITY_PASS:-}"
  ARBITER_LABEL="${ARBITER_LABEL:-Escalate to a higher-tier model}"
fi

# --- stack pack -------------------------------------------------------------------------------
# Selection order: RATCHET_STACK env > $HOOKS_DIR/stack/active (symlink or file naming the pack)
# > python-pytest. "active" may be a symlink to the pack, or a plain text file whose first
# non-comment line is the pack name (Git-Bash without developer mode cannot make symlinks).
_rt_pick_stack() {
  local marker="$HOOKS_DIR/stack/active" name=""
  if [ -n "${RATCHET_STACK:-}" ]; then
    printf '%s\n' "${RATCHET_STACK}"; return 0
  fi
  if [ -L "$marker" ] && command -v readlink >/dev/null 2>&1; then
    name=$(readlink "$marker" 2>/dev/null)
  elif [ -f "$marker" ]; then
    name=$(sed -e 's/\r$//' -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
             "$marker" 2>/dev/null | grep -v '^$' | head -n 1)
  fi
  name="${name##*/}"
  name="${name%.sh}"
  [ -n "$name" ] || name="python-pytest"
  printf '%s\n' "$name"
}

RATCHET_STACK="$(_rt_pick_stack)"
RATCHET_STACK="${RATCHET_STACK%$'\r'}"
_rt_stack_file="$HOOKS_DIR/stack/${RATCHET_STACK}.sh"
if [ ! -f "$_rt_stack_file" ]; then
  printf 'ratchet: NOTICE stack pack %s not found - falling back to generic\n' \
    "$_rt_stack_file" >&2
  RATCHET_STACK="generic"
  _rt_stack_file="$HOOKS_DIR/stack/generic.sh"
fi
if [ -f "$_rt_stack_file" ]; then
  # shellcheck disable=SC1090
  . "$_rt_stack_file"
else
  # Last resort: no stack pack on disk at all. Define the interface empty so every
  # command-needing gate SKIPs loudly instead of running an undefined string.
  printf 'ratchet: NOTICE no stack pack available - all stack commands are empty\n' >&2
  STACK_NAME="${STACK_NAME:-none}"
  VERIFY_CMD="${VERIFY_CMD:-}"; FAST_TEST_CMD="${FAST_TEST_CMD:-}"
  SCOPED_TEST_CMD="${SCOPED_TEST_CMD:-}"; RED_TEST_CMD="${RED_TEST_CMD:-}"
  COLLECT_TESTS_CMD="${COLLECT_TESTS_CMD:-}"; SECRETS_SCAN_CMD="${SECRETS_SCAN_CMD:-}"
  DEP_AUDIT_CMD="${DEP_AUDIT_CMD:-}"; FORMAT_CMD="${FORMAT_CMD:-}"
  FORMAT_EXTENSIONS="${FORMAT_EXTENSIONS:-}"; TEST_PATH_REGEX="${TEST_PATH_REGEX:-}"
  TEST_SURFACE_REGEX="${TEST_SURFACE_REGEX:-}"; FAILURE_LINE_REGEX="${FAILURE_LINE_REGEX:-}"
fi

# --- selftest ----------------------------------------------------------------------------------
if [ "${BASH_SOURCE[0]:-$0}" = "$0" ] && [ "${1:-}" = "--selftest" ]; then
  printf 'ratchet.config.sh selftest\n'
  printf '  RT_VERSION=%s\n  REPO_ROOT=%s\n  PROJECT_NAME=%s\n' "$RT_VERSION" "$REPO_ROOT" "$PROJECT_NAME"
  printf '  DOMAIN_NAME=%s\n  STACK=%s (%s)\n' "${DOMAIN_NAME:-?}" "$RATCHET_STACK" "${STACK_NAME:-?}"
  printf '  PIPELINE_DIR=%s CONTEXT_DIR=%s HOOKS_DIR=%s\n' "$PIPELINE_DIR" "$CONTEXT_DIR" "$HOOKS_DIR"
  for _v in RT_VERSION REPO_ROOT PIPELINE_DIR CONTEXT_DIR DEV_DIR CLAUDE_DIR HOOKS_DIR \
            EVIDENCE_DIR SECRETS_DIR RUN_ACTIVE RUN_START RUN_IDLE RUN_LAST_SEEN READY_TO_SHIP \
            PLAN_FILES AMENDMENTS FINDINGS VERIFY_LAST RED_BASELINE SHIP_CONSENT RECAP \
            CHECKPOINTS_DIR ESCALATIONS_DIR DISPATCH_DIR EVENTS_LOG METRICS_JSON CMD_LOG RUN_JOURNAL \
            CONTEXT_LIVE ACTIVE_LESSONS PENDING_ACTIONS BASE_BRANCH AGENT_BRANCH_PREFIX \
            MAX_STOP_RETRIES MAX_RUN_WORK_SECONDS IDLE_THRESHOLD_SECONDS ESCALATION_KEY \
            ESCALATION_TTL_SECONDS ESCALATION_LEDGER; do
    eval "_val=\${$_v:-}"
    if [ -z "$_val" ]; then printf '  FAIL: %s is empty\n' "$_v" >&2; exit 1; fi
  done
  printf '  all frozen names present: OK\n'
  exit 0
fi
